services:
  sonar:
    image: sonarqube:7.9.5-community
    container_name: sonar
    depends_on:
      - sonar-db
      - init
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5433/sonar
      SONAR_JDBC_USERNAME: sonartest
      SONAR_JDBC_PASSWORD: sonartest
      sonar.web.port: 9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    ulimits:
      nproc: 131072
      nofile:
        soft: 8192
        hard: 131072
    ports:
      - "9017:9000"

  init:
    image: bash
    container_name: init
    privileged: true
    user: root
    volumes:
      - ./sonarqube/init.sh:/mnt/init.sh
    command: [ "sh", "-e", "/mnt/init.sh" ]

  sonar-db:
    image: postgres:latest
    container_name: sonar-db
    environment:
      POSTGRES_USER: sonartest
      POSTGRES_PASSWORD: sonartest
    volumes:
      - sonar_postgresql:/var/lib/postgresql
      - sonar_postgresql_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_postgresql:
  sonar_postgresql_data: